/**
 * Qoder's own WebAssembly module, driven from plain Node.
 *
 * Qoder signs its requests with a wasm export rather than a documented
 * algorithm: `QoderContext.prepareInferRequest` builds the signed URL, the
 * full COSY header set, and a *sealed* request body, and
 * `decrypt_server_response` opens the payloads it gets back. None of that is
 * reimplemented here — the module is embedded verbatim (see
 * `vendor/artifacts.ts`, regenerated by `scripts/vendor-qoder-wasm.mjs`) and
 * invoked through the same wrappers the app itself uses.
 *
 * Two pieces come together to make the module callable:
 *
 * 1. **The wasm-bindgen glue**, taken verbatim from the app. The app ships an
 *    *unobfuscated* copy of it inside its own `out/main/main.js` bundle, so it
 *    needs no reverse engineering. It provides the linear-memory helpers, the
 *    JS import table, and `initSync`.
 * 2. **The wrappers** for the exports the glue's copy does not include —
 *    `QoderContext`, `RequestResult`, the credential helpers and
 *    `generate_runtime_auth_fields`. These are lifted from the app's
 *    *obfuscated* worker bundle and are kept byte-for-byte in spirit: the
 *    short identifier names, the stack-pointer dance and the
 *    `takeObject`/`getStringFromWasm0` protocol are exactly the SDK's, so a
 *    future Qoder release can be diffed against them.
 *
 * Glue and wrappers are concatenated into one function scope because the glue
 * keeps the instantiated exports in a module-local `wasm` binding that the
 * wrappers close over. `initSync` populates it, which is why the assembly is
 * built once and cached.
 *
 * @module dsh-llm-bridge/drivers/qoder/wasm
 */

import { QODER_AUTH_GLUE_BASE64, QODER_AUTH_WASM_BASE64 } from './vendor/artifacts.ts'

/** Logger sink for the glue's own `WASM` category (loads and traps). */
export interface QoderWasmLogger {
  info(...args: unknown[]): void
  warn(...args: unknown[]): void
  error(...args: unknown[]): void
  debug(...args: unknown[]): void
  trace(...args: unknown[]): void
}

/** One signed/serialized request the wasm produced. */
export interface QoderRequestResult {
  /** Absolute URL, with the wasm's own query parameters applied. */
  readonly url: string
  /** Request body; sealed unless the endpoint is unsigned. */
  readonly body: string
  /** Header map as the wasm builds it (a JS `Map`). */
  readonly headers: ReadonlyMap<string, string>
  /** Release the wasm-side allocation. Safe to call once. */
  free(): void
}

/** A wasm-side context: one per request (the server rejects reused signatures). */
export interface QoderContextHandle {
  /**
   * Build the inference request: signed URL, COSY headers, sealed body.
   * `modelSource` is the catalog's `source` field (`system` for the models
   * this driver serves).
   */
  prepareInferRequest(base: string, body: string, modelKey?: string, modelSource?: string): QoderRequestResult
  /** Build a non-inference request in `auth` or anonymous `sign` mode. */
  prepareRequest(
    base: string,
    path: string,
    method: string,
    mode: 'auth' | 'sign',
    body?: string,
    extra?: string,
  ): QoderRequestResult
  /** Re-seed the auth fields after a token refresh. */
  refreshAuthFields(userInfoJson: string): void
  /** Release the wasm-side context. Safe to call once. */
  free(): void
}

/** The surface of Qoder's auth wasm that this driver uses. */
export interface QoderWasmApi {
  /** Open a credential blob with a 16-character key. */
  credential_storage_decrypt(blob: string, key: string): string
  /** Seal a credential document with the same key (deterministic). */
  credential_storage_encrypt(plaintext: string, key: string): string
  /** Open a sealed server payload. Throws when the payload is not sealed. */
  decrypt_server_response(payload: string): string
  /**
   * Derive the per-session auth fields (`encrypt_user_info`, `key`) from the
   * account identity. They are *not* stored on disk — they are regenerated on
   * every launch, and every authenticated request is rejected without them.
   */
  generate_runtime_auth_fields(inputJson: string): string
  /** Instantiate a request-signing context. */
  createContext(machineId: string, cosyVersion: string, userInfoJson: string, clientMetadataJson: string): QoderContextHandle
  /** The module's instantiated exports; exposed for diagnostics and tests. */
  readonly exports: Readonly<Record<string, unknown>>
}

/**
 * Wrappers for the exports missing from the app's readable glue copy.
 *
 * Provenance: `@qoder-ai/qoder-agent-sdk/dist/_worker/qoder-worker-runtime.obf.mjs`
 * (the app's own worker bundle). Names, integer offsets and the
 * `WASM_VECTOR_LEN` protocol are preserved deliberately — this block is a
 * transcript of the SDK, not an independent implementation, so that a future
 * wasm upgrade can be diffed against it.
 */
const WRAPPERS = `
function credential_storage_decrypt(A,e){let t,i;try{const l=wasm.__wbindgen_add_to_stack_pointer(-16),
B=passStringToWasm0(A,wasm.__wbindgen_export2,wasm.__wbindgen_export3),c=WASM_VECTOR_LEN,
Q=passStringToWasm0(e,wasm.__wbindgen_export2,wasm.__wbindgen_export3),E=WASM_VECTOR_LEN;
wasm.credential_storage_decrypt(l,B,c,Q,E);
var n=getDataViewMemory0().getInt32(l+0,!0),r=getDataViewMemory0().getInt32(l+4,!0),
o=getDataViewMemory0().getInt32(l+8,!0),s=getDataViewMemory0().getInt32(l+12,!0),a=n,g=r;
if(s)throw a=0,g=0,takeObject(o);return t=a,i=g,getStringFromWasm0(a,g)
}finally{wasm.__wbindgen_add_to_stack_pointer(16),wasm.__wbindgen_export4(t,i,1)}}
function credential_storage_encrypt(A,e){let t,i;try{const l=wasm.__wbindgen_add_to_stack_pointer(-16),
B=passStringToWasm0(A,wasm.__wbindgen_export2,wasm.__wbindgen_export3),c=WASM_VECTOR_LEN,
Q=passStringToWasm0(e,wasm.__wbindgen_export2,wasm.__wbindgen_export3),E=WASM_VECTOR_LEN;
wasm.credential_storage_encrypt(l,B,c,Q,E);
var n=getDataViewMemory0().getInt32(l+0,!0),r=getDataViewMemory0().getInt32(l+4,!0),
o=getDataViewMemory0().getInt32(l+8,!0),s=getDataViewMemory0().getInt32(l+12,!0),a=n,g=r;
if(s)throw a=0,g=0,takeObject(o);return t=a,i=g,getStringFromWasm0(a,g)
}finally{wasm.__wbindgen_add_to_stack_pointer(16),wasm.__wbindgen_export4(t,i,1)}}
function decrypt_server_response(A){let t,i;try{const l=wasm.__wbindgen_add_to_stack_pointer(-16),
B=passStringToWasm0(A,wasm.__wbindgen_export2,wasm.__wbindgen_export3),c=WASM_VECTOR_LEN;
wasm.decrypt_server_response(l,B,c);
var n=getDataViewMemory0().getInt32(l+0,!0),r=getDataViewMemory0().getInt32(l+4,!0),
o=getDataViewMemory0().getInt32(l+8,!0),s=getDataViewMemory0().getInt32(l+12,!0),a=n,g=r;
if(s)throw a=0,g=0,takeObject(o);return t=a,i=g,getStringFromWasm0(a,g)
}finally{wasm.__wbindgen_add_to_stack_pointer(16),wasm.__wbindgen_export4(t,i,1)}}
function generate_runtime_auth_fields(A){let t,i;try{const l=wasm.__wbindgen_add_to_stack_pointer(-16),
B=passStringToWasm0(A,wasm.__wbindgen_export2,wasm.__wbindgen_export3),c=WASM_VECTOR_LEN;
wasm.generate_runtime_auth_fields(l,B,c);
var n=getDataViewMemory0().getInt32(l+0,!0),r=getDataViewMemory0().getInt32(l+4,!0),
o=getDataViewMemory0().getInt32(l+8,!0),s=getDataViewMemory0().getInt32(l+12,!0),a=n,g=r;
if(s)throw a=0,g=0,takeObject(o);return t=a,i=g,getStringFromWasm0(a,g)
}finally{wasm.__wbindgen_add_to_stack_pointer(16),wasm.__wbindgen_export4(t,i,1)}}
function _opt(s){return isLikeNone(s)?0:passStringToWasm0(s,wasm.__wbindgen_export2,wasm.__wbindgen_export3)}
class RequestResult{
  constructor(p){this.__wbg_ptr=p>>>0}
  free(){const p=this.__wbg_ptr;this.__wbg_ptr=0;wasm.__wbg_requestresult_free(p,0)}
  get headers(){return takeObject(wasm.requestresult_headers(this.__wbg_ptr))}
  _s(fn){let a=0,b=0;try{const r=wasm.__wbindgen_add_to_stack_pointer(-16);fn(r,this.__wbg_ptr);
    return a=getDataViewMemory0().getInt32(r+0,!0),b=getDataViewMemory0().getInt32(r+4,!0),getStringFromWasm0(a,b)
  }finally{wasm.__wbindgen_add_to_stack_pointer(16),wasm.__wbindgen_export4(a,b,1)}}
  get url(){return this._s(wasm.requestresult_url)}
  get body(){return this._s(wasm.requestresult_body)}
}
class QoderContext{
  constructor(machineId,cosyVersion,userInfoJson,clientMetaJson){
    try{const r=wasm.__wbindgen_add_to_stack_pointer(-16),
      p1=passStringToWasm0(machineId,wasm.__wbindgen_export2,wasm.__wbindgen_export3),l1=WASM_VECTOR_LEN,
      p2=passStringToWasm0(cosyVersion,wasm.__wbindgen_export2,wasm.__wbindgen_export3),l2=WASM_VECTOR_LEN,
      p3=passStringToWasm0(userInfoJson,wasm.__wbindgen_export2,wasm.__wbindgen_export3),l3=WASM_VECTOR_LEN;
    const p4=_opt(clientMetaJson),l4=WASM_VECTOR_LEN;
    wasm.qodercontext_new(r,p1,l1,p2,l2,p3,l3,p4,l4);
    const p=getDataViewMemory0().getInt32(r+0,!0),e=getDataViewMemory0().getInt32(r+4,!0);
    if(getDataViewMemory0().getInt32(r+8,!0))throw takeObject(e);
    this.__wbg_ptr=p>>>0}finally{wasm.__wbindgen_add_to_stack_pointer(16)}}
  free(){const p=this.__wbg_ptr;this.__wbg_ptr=0;wasm.__wbg_qodercontext_free(p,0)}
  prepareInferRequest(base,body,modelKey,modelSource){
    try{const r=wasm.__wbindgen_add_to_stack_pointer(-16),
      p1=passStringToWasm0(base,wasm.__wbindgen_export2,wasm.__wbindgen_export3),l1=WASM_VECTOR_LEN,
      p2=passStringToWasm0(body,wasm.__wbindgen_export2,wasm.__wbindgen_export3),l2=WASM_VECTOR_LEN;
    const p3=_opt(modelKey),l3=WASM_VECTOR_LEN,p4=_opt(modelSource),l4=WASM_VECTOR_LEN;
    wasm.qodercontext_prepareInferRequest(r,this.__wbg_ptr,p1,l1,p2,l2,p3,l3,p4,l4);
    const p=getDataViewMemory0().getInt32(r+0,!0),e=getDataViewMemory0().getInt32(r+4,!0);
    if(getDataViewMemory0().getInt32(r+8,!0))throw takeObject(e);
    return new RequestResult(p)}finally{wasm.__wbindgen_add_to_stack_pointer(16)}}
  prepareRequest(base,p,method,mode,body,extra){
    try{const r=wasm.__wbindgen_add_to_stack_pointer(-16),
      p1=passStringToWasm0(base,wasm.__wbindgen_export2,wasm.__wbindgen_export3),l1=WASM_VECTOR_LEN,
      p2=passStringToWasm0(p,wasm.__wbindgen_export2,wasm.__wbindgen_export3),l2=WASM_VECTOR_LEN,
      p3=passStringToWasm0(method,wasm.__wbindgen_export2,wasm.__wbindgen_export3),l3=WASM_VECTOR_LEN,
      p4=passStringToWasm0(mode,wasm.__wbindgen_export2,wasm.__wbindgen_export3),l4=WASM_VECTOR_LEN;
    const p5=_opt(body),l5=WASM_VECTOR_LEN,p6=_opt(extra),l6=WASM_VECTOR_LEN;
    wasm.qodercontext_prepareRequest(r,this.__wbg_ptr,p1,l1,p2,l2,p3,l3,p4,l4,p5,l5,p6,l6);
    const x=getDataViewMemory0().getInt32(r+0,!0),e=getDataViewMemory0().getInt32(r+4,!0);
    if(getDataViewMemory0().getInt32(r+8,!0))throw takeObject(e);
    return new RequestResult(x)}finally{wasm.__wbindgen_add_to_stack_pointer(16)}}
  refreshAuthFields(json){try{const r=wasm.__wbindgen_add_to_stack_pointer(-16),
    p=passStringToWasm0(json,wasm.__wbindgen_export2,wasm.__wbindgen_export3),l=WASM_VECTOR_LEN;
    wasm.qodercontext_refreshAuthFields(r,this.__wbg_ptr,p,l);
    const v=getDataViewMemory0().getInt32(r+0,!0);
    if(getDataViewMemory0().getInt32(r+4,!0))throw takeObject(v)
  }finally{wasm.__wbindgen_add_to_stack_pointer(16)}}
}`

/** What the assembled glue+wrapper scope hands back. */
interface AssembledScope {
  initSync(input: { module: Uint8Array }): Readonly<Record<string, unknown>>
  credential_storage_decrypt(blob: string, key: string): string
  credential_storage_encrypt(plaintext: string, key: string): string
  decrypt_server_response(payload: string): string
  generate_runtime_auth_fields(inputJson: string): string
  QoderContext: new (
    machineId: string,
    cosyVersion: string,
    userInfoJson: string,
    clientMetaJson: string,
  ) => {
    prepareInferRequest(base: string, body: string, modelKey?: string, modelSource?: string): QoderRequestResult
    prepareRequest(
      base: string, path: string, method: string, mode: string, body?: string, extra?: string,
    ): QoderRequestResult
    refreshAuthFields(userInfoJson: string): void
    free(): void
  }
}

const NOOP_LOGGER: QoderWasmLogger = {
  info() {}, warn() {}, error() {}, debug() {}, trace() {},
}

/** Assembly cache: the module is instantiated once per process. */
let cached: QoderWasmApi | undefined

/**
 * Instantiate the embedded module and return the callable surface.
 *
 * The instantiation is single-shot per process: the glue keeps its exports in
 * one local binding and `initSync` short-circuits on a second call, so caching
 * the assembled API also keeps the wrapper closures pointed at the live
 * instance.
 *
 * @param logger - receives the glue's own `WASM` category output. Defaults to
 *   a no-op sink; pass the plugin logger to surface load failures and traps.
 */
export function loadQoderWasm(logger: QoderWasmLogger = NOOP_LOGGER): QoderWasmApi {
  if (cached !== undefined) return cached

  const glue = Buffer.from(QODER_AUTH_GLUE_BASE64, 'base64').toString('utf8')
  const bytes = Buffer.from(QODER_AUTH_WASM_BASE64, 'base64')

  // `createCategoryLogger` is the glue's one external reference; it is passed
  // in as a parameter so the glue never reaches for an ambient global.
  const assemble = new Function(
    'createCategoryLogger',
    `${glue}${WRAPPERS}
return { initSync, credential_storage_decrypt, credential_storage_encrypt,
  decrypt_server_response, generate_runtime_auth_fields, QoderContext };`,
  ) as (makeLogger: (category: string) => QoderWasmLogger) => AssembledScope

  const makeLogger = (category: string): QoderWasmLogger => ({
    info: (...args: unknown[]) => logger.info(`[qoder-wasm:${category}]`, ...args),
    warn: (...args: unknown[]) => logger.warn(`[qoder-wasm:${category}]`, ...args),
    error: (...args: unknown[]) => logger.error(`[qoder-wasm:${category}]`, ...args),
    debug: (...args: unknown[]) => logger.debug(`[qoder-wasm:${category}]`, ...args),
    trace: (...args: unknown[]) => logger.trace(`[qoder-wasm:${category}]`, ...args),
  })

  const scope = assemble(makeLogger)
  const exports = scope.initSync({ module: bytes })

  cached = {
    exports,
    credential_storage_decrypt: (blob, key) => scope.credential_storage_decrypt(blob, key),
    credential_storage_encrypt: (plaintext, key) => scope.credential_storage_encrypt(plaintext, key),
    decrypt_server_response: payload => scope.decrypt_server_response(payload),
    generate_runtime_auth_fields: input => scope.generate_runtime_auth_fields(input),
    createContext: (machineId, cosyVersion, userInfoJson, clientMetadataJson) =>
      new scope.QoderContext(machineId, cosyVersion, userInfoJson, clientMetadataJson),
  }
  return cached
}

/**
 * Open a server payload, falling back to the raw text.
 *
 * Qoder seals *most* responses but not all: the inference SSE frames arrive as
 * plain JSON while `region/endpoints` and `model/list` are sealed. The app's
 * own SDK wraps every read in exactly this try/catch, and a driver that skips
 * the fallback turns a readable stream into silence.
 */
export function openServerPayload(api: QoderWasmApi, payload: string): string {
  try {
    return api.decrypt_server_response(payload)
  } catch {
    return payload
  }
}

/** Test seam: drop the cached instance so a fresh module can be assembled. */
export function resetQoderWasmCache(): void {
  cached = undefined
}
